In [ ]:
import torch
import torch.nn as nn

## Masking

In [ ]:
A = torch.randint(1,9,(10,10))
"""
Random tensor of shape M=10 and T=10

Total number of tokens N = M * T = 100

Shape of Mask = N^2 = (100,100)
"""

mask = [] # without cls token

index=0
for i in range(A.shape[0]):
  for j in range(A.shape[1]):

    mask.append([])

    for m in range(A.shape[0]):
      for n in range(A.shape[1]):
        
        if m == i or n ==j:
          mask[index].append(1)
        else:
          mask[index].append(0)
    index += 1

mask = torch.tensor(mask)

# pick a random token (out of 100 tokens)
print(mask[45].reshape(10,10))

# An example mask that incorporate cls tokens
wo_cls = torch.zeros(5,5)
print('\n',wo_cls)
wth_cls = nn.functional.pad(wo_cls,(1,0,1,0),value=1.0)
print('\n',wth_cls)

tensor([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

 tensor([[1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0.]])
